### ISSUE TITLE
I'm experiencing some issues

### ISSUE THREAD

**Issue by ph1lj-6321** [kevinmcaleer/cyberdog#1]
I'm experiencing some issues - when I use your cyberdog.py and index.html - I repeatedly get the following error, I'm using the latest release of phew (0.3) on the pico w. (I've tested it with various PC's, Pi400 and a Android tablet, on the PC the MSN site pops - strange)

What I see in the Shell  - 

2022-10-07 12:23:55 [info     / 136kB] starting DNS server on 192.168.4.1
2022-10-07 12:23:55 [info     / 134kB] > starting catch all dns server on port 53
2022-10-07 12:23:55 [info     / 132kB] > starting web server on port 80
2022-10-07 12:24:19 [info     / 118kB] > HEAD / (301 Moved Permanently) [134ms]
Task exception wasn't retrieved
future: <Task> coro= <generator object '_handle_request' at 2000a940>
Traceback (most recent call last):
  File "uasyncio/core.py", line 1, in run_until_complete
  File "/lib/phew/server.py", line 277, in _handle_request
AttributeError: 'NoneType' object has no attribute 'status'
2022-10-07 12:24:24 [info     / 130kB] > HEAD / (301 Moved Permanently) [247ms]
Task exception wasn't retrieved
future: <Task> coro= <generator object '_handle_request' at 200103c0>

Any thoughts ?

**Comment by johnmccabe** [comment]
This seems to be due to differences in how Android handles captive portals, it should return a 302 to the index route (`/`), rather than the 301 to `wrong_host_redirect`. Handling multiple different OS's/devices is a bit more complex, but the core of the logic here is an excellent starting point.
